services:
  db:
    image: postgis/postgis:15-3.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: breakchekrdb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server/utils/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  pgdata:
