steps:
  # 1. Install frontend dependencies
  - name: 'gcr.io/cloud-builders/npm'
    dir: '../client'
    args: ['install']
    id: 'Install frontend dependencies'

  # 2. Build frontend
  - name: 'gcr.io/cloud-builders/npm'
    dir: '../client'
    args: ['run', 'build']
    id: 'Build frontend'

  # 3. Copy frontend build to server/client-build
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo '📦 Copying frontend build to client-build...'
        rm -rf client-build
        mkdir -p client-build
        cp -r ../client/dist/* client-build/
        echo '✅ Frontend copied.'
    id: 'Copy frontend build'

  # 4. Install backend dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    id: 'Install backend dependencies'

  # 5. Build backend (if any)
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    id: 'Build backend'

  # 6. Run backend tests
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'test']
    id: 'Test backend'

  # 7. Deploy to App Engine (app.yaml is in same dir) quota increased to 1
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--version=prod', '--quiet']
    id: 'Deploy to App Engine'

options:
  logging: CLOUD_LOGGING_ONLY
timeout: '900s'
